"""Deterministic assembly generation from workload intent."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from .ir import WorkloadIntent


ALU_OPS = {"ADD", "SUB", "AND", "OR", "ADDI"}
MEMORY_OPS = {"LD", "ST"}
BRANCH_OPS = {"BEQ"}
IDLE_OPS = {"WFI"}


@dataclass(frozen=True)
class GeneratedWorkload:
    name: str
    assembly: str
    summary: dict[str, Any]


class Emitter:
    def __init__(self) -> None:
        self.lines: list[str] = []
        self.instruction_counts: dict[str, int] = {}
        self.category_counts: dict[str, int] = {
            "alu": 0,
            "memory": 0,
            "branch": 0,
            "idle": 0,
            "data_sram_access": 0,
            "dataflow_mmio_access": 0,
        }

    @property
    def instruction_count(self) -> int:
        return sum(self.instruction_counts.values())

    def comment(self, text: str = "") -> None:
        self.lines.append(f"# {text}" if text else "#")

    def emit(self, text: str, *, dataflow_mmio: bool = False, data_sram: bool = False) -> None:
        opcode = text.split(None, 1)[0].upper()
        self.lines.append(text)
        self.instruction_counts[opcode] = self.instruction_counts.get(opcode, 0) + 1

        if opcode in ALU_OPS:
            self.category_counts["alu"] += 1
        if opcode in MEMORY_OPS:
            self.category_counts["memory"] += 1
        if opcode in BRANCH_OPS:
            self.category_counts["branch"] += 1
        if opcode in IDLE_OPS:
            self.category_counts["idle"] += 1
        if dataflow_mmio:
            self.category_counts["dataflow_mmio_access"] += 1
        if data_sram:
            self.category_counts["data_sram_access"] += 1


def _small_imm(seed: int, *, minimum: int = 1, maximum: int = 7) -> int:
    span = maximum - minimum + 1
    return minimum + (seed % span)


def _emit_alu_chain(emitter: Emitter, chain_idx: int, depth: int) -> None:
    reg = 8 + (chain_idx % 4)
    emitter.comment(f"ALU dependency chain {chain_idx + 1}")
    emitter.emit(f"ADDI r{reg}, r0, {_small_imm(chain_idx)}")
    for step in range(depth):
        if step % 4 == 0:
            emitter.emit(f"ADD  r{reg}, r{reg}, r{reg}")
        elif step % 4 == 1:
            emitter.emit(f"SUB  r{reg}, r{reg}, r0")
        elif step % 4 == 2:
            emitter.emit(f"AND  r{reg}, r{reg}, r{reg}")
        else:
            emitter.emit(f"OR   r{reg}, r{reg}, r{reg}")


def _emit_memory_pair(emitter: Emitter, pair_idx: int) -> None:
    offsets = [0, 8, 12]
    offset = offsets[pair_idx % len(offsets)]
    src_reg = 4 + (pair_idx % 2)
    dst_reg = 6 + (pair_idx % 2)
    emitter.comment(f"Data SRAM store/load pair {pair_idx + 1}")
    emitter.emit(f"ADDI r{src_reg}, r0, {_small_imm(pair_idx + 3)}")
    emitter.emit(f"ST   r{src_reg}, [r0 + {offset}]", data_sram=True)
    emitter.emit(f"LD   r{dst_reg}, [r0 + {offset}]", data_sram=True)


def _emit_branch_probe(emitter: Emitter, probe_idx: int) -> None:
    reg = 12 + (probe_idx % 2)
    emitter.comment(f"Not-taken branch probe {probe_idx + 1}")
    emitter.emit(f"ADDI r{reg}, r0, 1")
    emitter.emit(f"BEQ  r{reg}, r0, 0")


def _emit_dataflow_macs(emitter: Emitter, macs: int) -> None:
    if macs == 0:
        return

    emitter.comment("Clear dataflow accumulator")
    emitter.emit("ADDI r6, r0, 2")
    emitter.emit("ST   r6, [r0 + 6]", dataflow_mmio=True)

    for idx in range(macs):
        a_value = _small_imm(idx + 1)
        b_value = _small_imm(idx + 3)
        emitter.comment(f"Dataflow MAC {idx + 1}: acc += {a_value} * {b_value}")
        emitter.emit(f"ADDI r1, r0, {a_value}")
        emitter.emit(f"ADDI r2, r0, {b_value}")
        emitter.emit("ADDI r3, r0, 1")
        emitter.emit("ST   r1, [r0 + 4]", dataflow_mmio=True)
        emitter.emit("ST   r2, [r0 + 5]", dataflow_mmio=True)
        emitter.emit("ST   r3, [r0 + 6]", dataflow_mmio=True)

    emitter.comment("Read accumulated dataflow result")
    emitter.emit("LD   r7, [r0 + 7]", dataflow_mmio=True)


def _emit_idle_windows(emitter: Emitter, idle_windows: int) -> None:
    for idx in range(idle_windows):
        emitter.comment(f"Idle hint window {idx + 1}")
        emitter.emit("WFI")


def generate_workload(intent: WorkloadIntent) -> GeneratedWorkload:
    emitter = Emitter()
    emitter.comment(f"Generated workload: {intent.name}")
    if intent.description:
        emitter.comment(intent.description)
    emitter.comment(f"Profile: {intent.profile}")
    emitter.comment("Generated by tools/gen_workload.py from a workload intent spec.")
    emitter.comment("")

    for chain_idx in range(intent.alu_chains):
        _emit_alu_chain(emitter, chain_idx, intent.dependency_depth)

    for pair_idx in range(intent.memory_pairs):
        _emit_memory_pair(emitter, pair_idx)

    for probe_idx in range(intent.branch_probes):
        _emit_branch_probe(emitter, probe_idx)

    _emit_dataflow_macs(emitter, intent.dataflow_macs)

    if intent.result_store and intent.dataflow_macs > 0:
        emitter.comment("Store dataflow result into normal data SRAM")
        emitter.emit("ST   r7, [r0 + 0]", data_sram=True)

    _emit_idle_windows(emitter, max(intent.idle_windows, 1))

    if emitter.instruction_count > intent.max_instructions:
        raise ValueError(
            f"Generated program has {emitter.instruction_count} instructions, "
            f"exceeding max_instructions={intent.max_instructions}"
        )

    summary = {
        "name": intent.name,
        "description": intent.description,
        "resolved_intent": intent.to_dict(),
        "instruction_count": emitter.instruction_count,
        "instruction_counts": dict(sorted(emitter.instruction_counts.items())),
        "category_counts": dict(sorted(emitter.category_counts.items())),
        "notes": [
            "Branch probes are generated as not-taken branches to keep execution bounded.",
            "Dataflow accesses use MMIO offsets 4, 5, 6, and 7.",
            "Data SRAM accesses avoid the dataflow MMIO window.",
        ],
    }
    return GeneratedWorkload(
        name=intent.name,
        assembly="\n".join(emitter.lines) + "\n",
        summary=summary,
    )
