#!/usr/bin/env python3
"""Generate a synthesis-friendly instruction ROM for one assembled workload."""

from __future__ import annotations

import argparse
from pathlib import Path


def read_memh(path: Path, depth: int) -> list[int]:
    words = [0 for _ in range(depth)]
    if not path.exists():
        raise FileNotFoundError(path)
    index = 0
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("//", 1)[0].split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("@"):
            index = int(line[1:], 16)
            continue
        if index >= depth:
            raise ValueError(f"{path}: program exceeds ROM depth {depth}")
        words[index] = int(line, 16) & 0xFFFF
        index += 1
    return words


def render_rom(words: list[int], module_name: str = "instr_rom") -> str:
    addr_width = max(1, (len(words) - 1).bit_length())
    lines = [
        "// Generated by tools/gen_synth_rom.py; do not edit by hand.",
        f"module {module_name} (",
        "  input  wire [31:0] addr,",
        "  output reg  [15:0] instr",
        ");",
        f"  wire [{addr_width - 1}:0] word_addr = addr[{addr_width + 1}:2];",
        "",
        "  always @* begin",
        "    case (word_addr)",
    ]
    for index, word in enumerate(words):
        if word != 0:
            lines.append(f"      {addr_width}'d{index}: instr = 16'h{word:04x};")
    lines.extend(
        [
            "      default: instr = 16'h0000;",
            "    endcase",
            "  end",
            "endmodule",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--memh", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--depth", type=int, default=64)
    args = parser.parse_args()

    words = read_memh(args.memh, args.depth)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_rom(words), encoding="utf-8")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
