#!/usr/bin/env python3
"""Run Yosys synthesis for the mobile CPU and emit reusable synthesis artifacts."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

from gen_synth_rom import read_memh, render_rom
from synth_metrics import extract_metrics, write_summary


RTL_FILES = [
    "rtl/mobile_cpu_pkg.sv",
    "rtl/clock_gate.sv",
    "rtl/power_controller.sv",
    "rtl/fetch_unit.sv",
    "rtl/decode_unit.sv",
    "rtl/regfile.sv",
    "rtl/execute_unit.sv",
    "rtl/load_store_unit.sv",
    "rtl/data_sram.sv",
    "rtl/dataflow_unit.sv",
    "rtl/data_bus_interconnect.sv",
    "rtl/mobile_cpu_top.sv",
]

RTL_FILES_WITH_MEMORY_MACROS = [
    "rtl/mobile_cpu_pkg.sv",
    "rtl/clock_gate.sv",
    "rtl/power_controller.sv",
    "rtl/fetch_unit.sv",
    "rtl/decode_unit.sv",
    "rtl/regfile.sv",
    "rtl/execute_unit.sv",
    "rtl/load_store_unit.sv",
    "rtl/dataflow_unit.sv",
    "rtl/data_bus_interconnect.sv",
    "rtl/mobile_cpu_top.sv",
]

MEMORY_MACRO_BLACKBOXES = [
    "macros/memory/instr_rom_blackbox.v",
    "macros/memory/data_sram_blackbox.v",
]


def tool_path(tool: str) -> str:
    resolved = shutil.which(tool)
    if resolved:
        return resolved
    print(
        f"Required tool '{tool}' was not found.\n"
        "Install Yosys first, for example on macOS:\n\n"
        "  brew install yosys\n\n"
        "The existing RTL/UPF/2416 flows do not require Yosys; only the synthesis layer does.",
        file=sys.stderr,
    )
    raise SystemExit(127)


def render_yosys_script(
    rtl_files: list[str],
    rom_path: Path | None,
    out_dir: Path,
    top: str,
    mapped: bool,
    liberty: Path | None,
    macro_blackboxes: list[Path],
) -> tuple[str, str, str]:
    stem = "mobile_cpu_mapped" if mapped else "mobile_cpu_synth"
    json_path = out_dir / f"{stem}.json"
    netlist_path = out_dir / ("mobile_cpu_mapped.v" if mapped else "mobile_cpu_gate.v")
    lines = [
        "# Generated by tools/run_yosys_synth.py",
    ]
    if mapped:
        if liberty is None:
            raise ValueError("--liberty is required when --mapped is used")
        lines.append(f"read_liberty -lib {liberty}")
        lines.extend(f"read_verilog -sv {path}" for path in macro_blackboxes)
    lines.extend(f"read_verilog -sv {path}" for path in rtl_files)
    if rom_path is not None:
        lines.append(f"read_verilog -sv {rom_path}")
    lines.extend(
        [
            f"hierarchy -check -top {top}",
            f"synth -top {top}",
        ]
    )
    if mapped:
        lines.extend(
            [
                f"dfflibmap -liberty {liberty}",
                f"abc -liberty {liberty}",
            ]
        )
    lines.extend(
        [
            "clean",
            "check",
            f"write_json {json_path}",
            f"write_verilog -noattr {netlist_path}",
        ]
    )
    return "\n".join(lines) + "\n", str(json_path), str(netlist_path)


def render_stdcell_sim_script(liberty: Path, out_path: Path) -> str:
    return "\n".join(
        [
            "# Generated by tools/run_yosys_synth.py",
            f"read_liberty -ignore_miss_func -ignore_miss_dir -ignore_miss_data_latch {liberty}",
            f"write_verilog -noattr {out_path}",
            "",
        ]
    )


def run(args: argparse.Namespace) -> None:
    yosys = tool_path(args.yosys)
    args.out.mkdir(parents=True, exist_ok=True)

    rom_path: Path | None = None
    rtl_files = RTL_FILES
    macro_blackboxes: list[Path] = []
    if args.mapped and args.memory_macros:
        rtl_files = RTL_FILES_WITH_MEMORY_MACROS
        macro_blackboxes = args.macro_blackbox or [Path(path) for path in MEMORY_MACRO_BLACKBOXES]
    else:
        rom_path = args.out / "instr_rom_synth.sv"
        words = read_memh(args.program, args.rom_depth)
        rom_path.write_text(render_rom(words), encoding="utf-8")

    script_path = args.out / "mobile_cpu_synth.ys"
    script, synth_json_name, netlist_name = render_yosys_script(
        rtl_files,
        rom_path,
        args.out,
        args.top,
        args.mapped,
        args.liberty,
        macro_blackboxes,
    )
    script_path.write_text(script, encoding="utf-8")

    log_path = args.out / "mobile_cpu_synth.log"
    command = [yosys, "-s", str(script_path)]
    with log_path.open("w", encoding="utf-8") as log:
        result = subprocess.run(command, stdout=log, stderr=subprocess.STDOUT, text=True)
    if result.returncode != 0:
        print(f"Yosys synthesis failed; see {log_path}", file=sys.stderr)
        raise SystemExit(result.returncode)

    stdcell_sim_path: Path | None = None
    if args.mapped and args.stdcell_sim and args.liberty:
        stdcell_sim_path = args.stdcell_sim
        stdcell_sim_path.parent.mkdir(parents=True, exist_ok=True)
        stdcell_script_path = args.out / "stdcell_sim.ys"
        stdcell_script_path.write_text(render_stdcell_sim_script(args.liberty, stdcell_sim_path), encoding="utf-8")
        stdcell_log_path = args.out / "stdcell_sim.log"
        with stdcell_log_path.open("w", encoding="utf-8") as log:
            sim_result = subprocess.run([yosys, "-s", str(stdcell_script_path)], stdout=log, stderr=subprocess.STDOUT, text=True)
        if sim_result.returncode != 0:
            print(f"Standard-cell simulation model generation failed; see {stdcell_log_path}", file=sys.stderr)
            raise SystemExit(sim_result.returncode)

    synth_json_path = Path(synth_json_name)
    yosys_json = json.loads(synth_json_path.read_text(encoding="utf-8"))
    metrics = extract_metrics(yosys_json, source=str(synth_json_path), workload=args.workload)
    if args.mapped:
        metrics["mapping"] = {
            "mapped": True,
            "liberty": str(args.liberty),
            "memory_macros": bool(args.memory_macros),
            "macro_blackboxes": [str(path) for path in macro_blackboxes],
        }

    metrics_stem = "mobile_cpu_mapped_metrics" if args.mapped else "mobile_cpu_synth_metrics"
    metrics_path = args.out / f"{metrics_stem}.json"
    summary_path = args.out / f"{metrics_stem}.md"
    metrics_path.write_text(json.dumps(metrics, indent=2) + "\n", encoding="utf-8")
    write_summary(metrics, summary_path)

    manifest = {
        "top": args.top,
        "workload": args.workload,
        "program": str(args.program),
        "yosys": yosys,
        "script": str(script_path),
        "log": str(log_path),
        "mapped": bool(args.mapped),
        "memory_macros": bool(args.memory_macros),
        "liberty": str(args.liberty) if args.liberty else "",
        "stdcell_sim": str(stdcell_sim_path) if stdcell_sim_path else "",
        "netlist": netlist_name,
        "json": str(synth_json_path),
        "metrics": str(metrics_path),
        "summary": str(summary_path),
    }
    (args.out / "mobile_cpu_synth_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {netlist_name}")
    print(f"wrote {metrics_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--yosys", default="yosys")
    parser.add_argument("--program", type=Path, required=True)
    parser.add_argument("--workload", default="builtin")
    parser.add_argument("--out", type=Path, default=Path("build/synth"))
    parser.add_argument("--top", default="mobile_cpu_top")
    parser.add_argument("--rom-depth", type=int, default=64)
    parser.add_argument("--mapped", action="store_true")
    parser.add_argument("--liberty", type=Path)
    parser.add_argument("--memory-macros", action="store_true")
    parser.add_argument("--macro-blackbox", action="append", type=Path)
    parser.add_argument("--stdcell-sim", type=Path)
    args = parser.parse_args()
    run(args)


if __name__ == "__main__":
    main()
